dark_theme: false
autoload_model: false
max_new_tokens: 2000
max_new_tokens_min: 1
max_new_tokens_max: 2000
seed: -1
character: None
name1: You
name2: Assistant
context: You are a helpful AI assistant.
greeting: ''
turn_template: ''
custom_stopping_strings: ''
stop_at_newline: false
add_bos_token: true
ban_eos_token: false
skip_special_tokens: true
truncation_length: 16384
truncation_length_min: 0
truncation_length_max: 16384
mode: default
start_with: ''
chat_style: cai-chat
instruction_template: Vicuna-v1.1
chat-instruct_command: 'Continue the chat dialogue below. Write a single reply for
  the character "<|character|>".


  <|prompt|>'
chat_generation_attempts: 1
chat_generation_attempts_min: 1
chat_generation_attempts_max: 10
default_extensions: []
chat_default_extensions:
- gallery
preset: simple-1
prompt: QA
