os: linux
language: generic
services:
  - docker

if: branch = master

matrix:
  include:
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/commitlint
        - WORKING_DIR=commitlint

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - cd $WORKING_DIR
  - docker build . -t $DOCKER_REPO:latest
  - docker push $DOCKER_REPO:latest
