os: linux
language: generic
services:
  - docker

if: branch = master

matrix:
  include:
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/commitlint
        - WORKING_DIR=commitlint
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/auto-changelog
        - WORKING_DIR=auto-changelog
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/cppdev
        - WORKING_DIR=cppdev
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/slatedocs
        - WORKING_DIR=slatedocs
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/wg
        - WORKING_DIR=wg
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/docker-buildx
        - WORKING_DIR=docker-buildx
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/cuda-python
        - WORKING_DIR=cuda-python
    - os: linux
      env:
        - DOCKER_REPO=triggerhappy/libra-gpu
        - WORKING_DIR=libra-gpu

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - cd $WORKING_DIR
  - docker build . -t $DOCKER_REPO:latest
  - docker push $DOCKER_REPO:latest
